-- PostgreSQL schema and seed data for database MiniGithub.
-- Create the database once before running this file:
--   createdb -U postgres MiniGithub
-- Then apply this file while connected to MiniGithub:
--   psql -U postgres -d MiniGithub -f schema.sql

BEGIN;

DROP TABLE IF EXISTS activities CASCADE;
DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS follows CASCADE;
DROP TABLE IF EXISTS stars CASCADE;
DROP TABLE IF EXISTS file_versions CASCADE;
DROP TABLE IF EXISTS files CASCADE;
DROP TABLE IF EXISTS repositories CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    bio TEXT,
    skills VARCHAR(255),
    role VARCHAR(20) NOT NULL DEFAULT 'DEVELOPER',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE repositories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    visibility VARCHAR(20) NOT NULL DEFAULT 'PUBLIC',
    language VARCHAR(50) NOT NULL DEFAULT 'Java',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repository_id BIGINT NOT NULL REFERENCES repositories(id) ON DELETE CASCADE,
    filename VARCHAR(255) NOT NULL,
    filetype VARCHAR(50),
    current_version_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE file_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id BIGINT NOT NULL REFERENCES files(id) ON DELETE CASCADE,
    version_number INT NOT NULL,
    content_path TEXT NOT NULL,
    file_size BIGINT NOT NULL DEFAULT 0,
    change_note TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE files
    ADD CONSTRAINT files_current_version_fk
    FOREIGN KEY (current_version_id) REFERENCES file_versions(id);

CREATE TABLE stars (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    repository_id BIGINT NOT NULL REFERENCES repositories(id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_user_repo_star UNIQUE (user_id, repository_id)
);

CREATE TABLE follows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    followee_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_follower_followee UNIQUE (follower_id, followee_id)
);

CREATE TABLE comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    repository_id BIGINT NOT NULL REFERENCES repositories(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    action_type VARCHAR(50) NOT NULL,
    target_id BIGINT,
    details VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Seed accounts use password "password123" except admin, which uses "admin123".
INSERT INTO users (id, username, email, password_hash, bio, skills, role, status) VALUES
(1, 'admin', 'admin@versiontree.com', '$2a$10$7EqJtq98hPqEX7fNZaFWoO9Z3b5g4o4sE9sS3QhD8m5pYkJvG8b5K', 'Platform Administrator', 'Java, Spring, J2EE, PostgreSQL', 'ADMIN', 'ACTIVE'),
(2, 'alex_dev', 'alex@vt.edu', '$2a$10$7EqJtq98hPqEX7fNZaFWoO9Z3b5g4o4sE9sS3QhD8m5pYkJvG8b5K', 'Third Year CS Student & Open Source Enthusiast', 'Java, C++, Python, Data Structures', 'DEVELOPER', 'ACTIVE'),
(3, 'sarah_coder', 'sarah@vt.edu', '$2a$10$7EqJtq98hPqEX7fNZaFWoO9Z3b5g4o4sE9sS3QhD8m5pYkJvG8b5K', 'Backend Developer & Java Architect', 'Spring Boot, Hibernate, PostgreSQL, REST', 'DEVELOPER', 'ACTIVE');

INSERT INTO repositories (id, owner_id, name, description, visibility, language) VALUES
(1, 2, 'Mini-Java-Compiler', 'A lightweight Java lexer and AST parser built for academic demonstration.', 'PUBLIC', 'Java'),
(2, 2, 'Data-Structure-Visualizer', 'Interactive visualization of trees, graphs, and heap data structures.', 'PUBLIC', 'Java'),
(3, 3, 'Smart-Budget-Manager', 'Web application for managing personal finances and generating reports.', 'PUBLIC', 'Java');

INSERT INTO files (id, repository_id, filename, filetype) VALUES
(1, 1, 'Lexer.java', 'JAVA'),
(2, 1, 'Parser.java', 'JAVA');

INSERT INTO file_versions (id, file_id, version_number, content_path, file_size, change_note) VALUES
(1, 1, 1, 'vt_storage/repo_1_file_1_v1_Lexer.java', 1024, 'Initial commit of lexical analyzer'),
(2, 1, 2, 'vt_storage/repo_1_file_1_v2_Lexer.java', 2048, 'Added token stream list return type'),
(3, 2, 1, 'vt_storage/repo_1_file_2_v1_Parser.java', 2048, 'Initial AST parser implementation');

UPDATE files SET current_version_id = 2 WHERE id = 1;
UPDATE files SET current_version_id = 3 WHERE id = 2;

INSERT INTO stars (user_id, repository_id) VALUES (3, 1), (2, 3);
INSERT INTO follows (follower_id, followee_id) VALUES (3, 2);
INSERT INTO comments (user_id, repository_id, content) VALUES
(3, 1, 'Great Lexer implementation! Clean token parsing logic.'),
(2, 3, 'Are you planning to add multi-currency support?');
INSERT INTO activities (user_id, action_type, target_id, details) VALUES
(2, 'CREATE_REPO', 1, 'Created repository Mini-Java-Compiler'),
(3, 'STAR_REPO', 1, 'Starred repository Mini-Java-Compiler'),
(3, 'COMMENT', 1, 'Commented on Mini-Java-Compiler');

SELECT setval(pg_get_serial_sequence('users', 'id'), (SELECT MAX(id) FROM users));
SELECT setval(pg_get_serial_sequence('repositories', 'id'), (SELECT MAX(id) FROM repositories));
SELECT setval(pg_get_serial_sequence('files', 'id'), (SELECT MAX(id) FROM files));
SELECT setval(pg_get_serial_sequence('file_versions', 'id'), (SELECT MAX(id) FROM file_versions));

COMMIT;
